info:
  version: 1.0.0
  description: NEF initial local configuration

configuration:
  sbi:
    scheme: http # The protocol for sbi (http or https)
    registerIPv4: 127.0.0.5 # IP used to register to NRF
    bindingIPv4: 127.0.0.5  # IP used to bind the service
    port: 8000 # port used to bind the service
  nrfUri: http://127.0.0.10:8000 # A valid URI of NRF
  serviceList: # the SBI services provided by this NEF
    - serviceName: nnef-pfdmanagement # Nnef_PFDManagement Service


# the kind of log output
  # debugLevel: how detialed to output, value: trace, debug, info, warn, error, fatal, panic
  # ReportCaller: enable the caller report or not, value: true or false
logger:
  NEF:
    debugLevel: info
    ReportCaller: false
  PathUtil:
    debugLevel: info
    ReportCaller: false
  OpenApi:
    debugLevel: info
    ReportCaller: false
