info:
  version: 1.0.0
  description: NEF initial local configuration

configuration:
  sbi:
    scheme: http
    registerIPv4: 127.0.0.1 # IP used to register to NRF
    bindingIPv4: 127.0.0.1  # IP used to bind the service
    port: 29505
  timeFormat: 2019-01-02 15:04:05
  nrfUri: http://localhost:29510
  serviceList:
    - serviceName: nnef-pfdmanagement

logger:
  NEF:
    debugLevel: info
    ReportCaller: false
  PathUtil:
    debugLevel: info
    ReportCaller: false
  OpenApi:
    debugLevel: info
    ReportCaller: false
