info:
  version: 1.0.0
  description: NEF initial local configuration

configuration:
  sbi:
    scheme: http
    registerIPv4: 127.0.0.5 # IP used to register to NRF
    bindingIPv4: 127.0.0.5  # IP used to bind the service
    port: 8000
  timeFormat: 2019-01-02 15:04:05
  nrfUri: http://127.0.0.10:8000
  serviceList:
    - serviceName: nnef-pfdmanagement

logger:
  NEF:
    debugLevel: info
    ReportCaller: false
  PathUtil:
    debugLevel: info
    ReportCaller: false
  OpenApi:
    debugLevel: info
    ReportCaller: false
